---
title: "Reviewer Comments (Scientific Reports)"
author: "Brad Duthie"
date: "30 December 2019"
output:
  pdf_document: default
  html_document: default
---




Reviewer 1 comment 1
================================================================================

This paper considers timely questions concerning the stability of complex systems, mainly using random matrix theory. The central problem consists in studying the stability of random matrices which were originally seen as random community matrices from ecology. In a seminal paper, R May challenged the consensus that complexity begets stability in complex ecosystems. These issues are of current concern in ecology. Most of the works dealing with such problems (either for stability or feasibility) consider networks of high species richness S, and develop or use techniques and results from random matrix theory in the large S limit, like e.g. Girko circular law that describes the asymptotic behavior of the related spectra measures (a system is stable when all of its eigenvalues have negative real parts).

The paper of Duthie is interesting since it deals with finite size systems where S is not too large. Mathematically, the author focus on random matrices of the form D A-id where D is a random diagonal matrix and A is a random matrix having i.i.d. centered entries. The author suggests numerically that stability is enhanced by multiplying A by D. This idea seems to be new. 

Author response to Reviewer 1 comment 1
================================================================================

I thank the reviewer for these comments. I share their belief that the issues in this paper are of current concern, and that the ideas presented in this manuscript are, to the best of my knowledge, novel.

Reviewer 1 comment 2
================================================================================

Recent works dealing with similar models in the large S limit have been published recently (Gibbs et al (2018) and Ahmadian (2018). Such works are not dealing with finite S and focus on limiting spectral measures. On the other hand, real empirical ecological networks have finite sizes S, so that the paper might be of practical interest for ecologists dealing with empirical data. In this setting, most interaction weights that define Lotka-Volterra dynamics are unknown at present time, and a natural idea consists in randomizing such weights to arrive at random community matrices of finite size, see, e.g. Ensemble ecosystem modeling for predicting ecosystem response to predator reintroduction, Baker et al. (2016) Conservation Biology, Volume 31, No. 2, 376–384.

Author response to Reviewer 1 comment 2
================================================================================

I again thank the reviewer for their comments. I agree that it is especially relevant that my manuscript focuses on finite S values, and I have made more emphasis on this point in my revision (e.g., L48, L88, L209, L234). In particular, in addition to the statement on L48, I now state more explicitly in describing the methods that "the objective is to determine the effect of $\gamma$ as system complexity increases toward the boundary at which stability is realistic for a finite system." (L88)

Reviewer 1 comment 3
================================================================================

In summary I think that the paper is interesting and timely, but I strongly recommend that the author considers also empirical webs (like for example those given in Dougoud et al. (2018)), the feasibility of equilibria in large ecosystems: A primary but neglected concept in the complexity-stability debate, PLoS Comput. Biol, and check numerically if the observation that variations of component responses rates enhance stability and feasibility is valid in experimentally observed webs. The author should also test this hypothesis on standard webs models for structured food web models like the niche, or the nested-hierarchy random web models.

Author response to Reviewer 1 comment 3
================================================================================

I agree with the relevance of Dougoud et al. (2018), and have made appropriate links to their results on feasibility (L143, L274). Nevertheless, one major result of my manuscript is that varying component response rates (i.e., $\gamma$) only affect stability, not feasibility (L148). Hence, Reviewer 1 is incorrect that my conclusions concerning varying component response rates should be expected to enhance feasibility in experimentally observed food webs (and therefore that stability should be enhanced for biologically realistic ecological communities in which all population densities are positive). Checking for validity in empirical food webs is therefore not entirely appropriate because the consequences of such an investigation would have negligible practical application (but, as I note in the Discussion L194, empirical food webs do not exist in a vacuum, and instead are parts of larger systems within which component response rate variation might indeed be relevant).

I welcome Reviewer 1's call for expanding the scope of models considered for simulations, which was also recommended by Reviewer 2. Nevertheless, my manuscript focuses broadly on complex systems rather than only on pure ecological systems, so I have revised my manuscript to test more general models of common network structures. In terms of ecological models, in addition to random competition, mutualism, and predator-prey networks, I have now also included a cascade food web model (which is a foundation for the extended niche and nested-heirarchy models that Reviewer 1 mentions; Williams and Martinez 2000). Other network types that I have incorporated into my revision include small-world networks (Watts and Strogatz 1998) and scale-free networks (Albert and Barab\'{a}si 2002). Overall, the structured networks that I now include in the main text and supporting information encompass a wide range of physical, biological, and social systems. Results for thse simulations are presented in a new section entitled, "Simulations of structured M across S" (L123). Methods for constructing small-world (L247), scale-free (L260), and cascade food web (L268) networks are now explained, with additional details and figures now in the Supplemental Information. The results from these structured networks match those of the random networks; variation in $\gamma$ increases the number of stable systems given sufficiently high system complexity, thereby further showing the generality of my results across complex systems.

Feasibility and how it relates to ecological systems is explained on L141, with discussion starting on L188 for how this relates to ecological systems. Full details of these results have also been added to the supporting information, and code for building structured networks is publicly available as a documented R package on GitHub (https://github.com/bradduthie/RandomMatrixStability) and accompanying website (https://bradduthie.github.io/RandomMatrixStability).

Reviewer 1 comment 4
================================================================================

Comment:

The manuscript is well written. I have just a remark concerning Figures 3 and 4. The black line is
intended to show the proportion of systems that are stable when the variance is positive but would
be unstable for zero variance. Is the author considering the conditional probability that A-id is
unstable given that DA-id is stable ? I think that this point should be explained in more details.

Author response to Reviewer 1 comment 3
================================================================================

Reviewer 1 is correct that the line illustrates the conditional probability that $A$ is unstable given that $M = \gamma A$ is stable. In other words, the proportion of complex systems found to be stable, but which would have been unstable if it were not for the variation in component response rates. 

I have explained the result shown by the black line of Figures 3 (now 4), and the former figure 4 (now in the SI), now more clearly in my revision (L420).

Reviewer 2 comment 1
================================================================================

The manuscript explores the stability of matrices of the form

$A = diag(\gamma)  M$,

where gamma is an S-component vector, diag(gamma) is the diagonal matrix with gamma along its diagonal, \* denotes matrix multiplication, and M is a circular random matrix (independently and randomly sampled offdiagonal entries with mean 0 and variance V=C*sigma^2 where C is the connectance and sigma^2 the variance of nonzero entries; and with all diagonal entries equal to -1). The main claim is that whenever the random matrix M has parameters putting it near the boundary of stability and instability, the likelihood of A being stable is increased by having a larger variance in gamma.

The manuscript is very clear and its results were easily reproducible. My concerns are threefold: first, there is no attempt at an analytical understanding, making the breadth of the results difficult to judge; second, the numerical exploration is restricted to a very narrow class of random matrices, further hampering a good appreciation of the results' breadth; and third, it feels as if the effect of response rate variation was a second- or even third-order effect, and thus only of minor importance in explaining the stability of large complex systems. Below I elaborate on each of these concerns in turn.

Author response to Reviewer 2 comment 1
================================================================================

I thank Reviewer 2 for their helpful comments. In my revision, I have provided more analytical context, expanded the types of networks explored (see also Author response to Reviewer 1 comment 3), and further clarified the role of response rate variation. I explain these changes in more detail with the reviewer's elaborated concerns below. 

Reviewer 2 comment 2
================================================================================

The results crucially build on the matrices being dangerously close to the stability boundary. At that point, minor fluctuations in the position of the leading eigenvalue can make or break a system. In fact, there are known results on the uncertainty in the leading eigenvalue's position - but, to my knowledge, those are only available for circular matrices (here: constant gamma). I am wondering whether combining those with the methods of Gibbs et al. (2018) could perhaps be used to gain further understanding. In either case, the manuscript would of course be much stronger with analytical results, but I do realize this may be uncharted territory.

Author response to Reviewer 2 comment 2
================================================================================

I appreciate these comments, and have tried to provide a more analytical explanation of the changes introduced by \gamma (L53-L64), including a new subsection explaining the effect of variation in $\gamma$ on the covariation of M (L65-L81). I agree that these analytical results improve the manuscript, and I think that they are particularly useful in setting the stage for the numerical simulations that now follow. In making these changes, I have slightly adjusted the notation so that the text is more readable. 

As Reviewer 2 correctly points out, my focus is on finite values of S and $\sigma$, in which complexity is gradually increased until it is dangerously close to the stability boundary. Given this focus, analytically demonstrating my central result (that variation in $X$ when $M = XA$ increases the probability of finding a stable $M$) would require some sort of comparison between the probability distributions of eigenvalues for $M$ and $A$. For circular matrices in which elements are i.i.d ($A$), it has been proved that eigenvalues are distributed uniformly within a known boundary of support of the spectral density (Tao and Vu 2010). While recent papers have found the support for more general types of random matrices that include the form $M = AX$ (e.g, Gibbs et al. 2018; Neri and Metz 2012; Ahmadian et al. 2015), to the best of my knowledge, finding the actual density of eigenvalues within the support has not been attempted. This likely matters because for finite S, even though the real boundary of the support might be positive for both $M$ and $A$ (implying instability as $S \to \infty$; Grilli et al. 2017), the right-most eigenvalue for a system still might be less than zero.

Reviewer 2 is correct that this is uncharted territory, and after spending a lot of time considering the possibility of an analytical demonstration of my main results, I am convinced that such a demonstration is beyond the scope of this manuscript. My approach follows others with similar objectives. For example, Sinha (2005) also used a numerical approach to understand the stability of small-world networks (in contrast to the classic random networks of May).

Reviewer 2 comment 3
================================================================================

Since numerical explorations are used in lieu of analytical ones, I would look at a broader class of matrices M. For example, the average pairwise correlation rho between the (i,j)th and (j,i) th matrix entries is known to strongly affect the local stability of a random matrix - in the large S limit, the leading eigenvalue converges to 

$\lambda = \sqrt{SV}*(+\rho)$.

I did some preliminary exploration of having different rho values, and this did not change the Author's results. So adding this new aspect to the manuscript would strengthen its results. I would also maybe consider matrices with even more structure - e.g., varying diagonal entries in M, or having different means/variances in the top and bottom triangles (corresponding to food webs with cascade structures; Allesina et al. 2015 Nature Communications).

Author response to Reviewer 2 comment 3
================================================================================

These were very helpful comments, and I have embraced them wholeheartedly in my revision. I am especially grateful to Reviewer 2 for doing a bit of preliminary exploration themselves to suggest improvements. I have now included a full section devoted to the role of $\rho$ on stability, and run simulations for different values of $\rho$, as suggested. Reviewer 2 is correct that the nonzero $\rho$ values do not change my results, but an analysis of stability across $\rho$ values also revealed an interesting pattern. While the relationship between $\rho$ and the leading eigenvalue is linear for circular matrices ($A$), it is convex when $\gamma$ is included such that $M = \gamma A$. I have now included these results into the main text of the manuscript, as I believe that they are important. 

As suggested, I also considered matrices with even more structure, performing a new simulations on each. Specifically, I have simulated three broad classes of structured networks that are widespread in physical, social, and biological systems. These include food webs with cascade structures (e.g., Williams and Martinez 2000), small-world networks (Watts and Strogatz 1998), and scale-free networks (Albert and Barab\'{a}si 2002). Results for these networks are presented in L123-L140, and methods are explained in L247-L273, and in the Supplemental Information. Overall, these structured networks were affected by variation in $\gamma$ in the same way as random networks (increasing stability given sufficiently high complexity).

Reviewer 2 comment 4
================================================================================

Finally, the general relevance of the results is hampered by being confined to a narrow parameter space, and even there the fraction of occurrences where var(gamma) makes a difference is minuscule. Looking at Figure 3, the only cases in which there is an appreciable effect of a variance in the gammas is when only a small handful of the matrices end up being stable in the first place. As such, var(gamma) only makes a difference when there is not much difference to be made anyway, because the vast majority of matrices end up unstable regardless of the magnitude of var(gamma). In light of this, I would be much more careful with the manuscript's framing - in particular, I would change the title to express better that we are dealing with second-order effects, and would not say in the Abstract that system stability is "markedly increased" by variation in the gammas. 

Author response to Reviewer 2 comment 4
================================================================================

While I agree that the effect of $var(\gamma)$ is restricted to a small proportion systems at the margins of stability, I would argue that this effect is actually of quite general relevance because of the breadth of complex systems to which my results apply. Addressing Reviewer 2's previous comment helped emphasise this; the effect of variation in $\gamma$ on stability, while small in overall magnitude, is predicted to be general across any physical, social, or biological network. Since nearly all such networks will have components that vary in the rate at which they respond to perturbation, my results contribute to a general understanding of system stability.

As recommended, I have changed the title, which now makes it more clear that the effects on stability are restricted to highly complex finite systems, while still retaining an emphasis on generality across systems. I have also removed the word "markedly" from the abstract, as recommended. 

Reviewer 3 commment 1
================================================================================

Remarks to the author:

This manuscript describe the effect of variation in the response rate of individual systems to the stability of a complex system by A. Bradley Duthie. The manuscript is well-written and the calculations, codes and so on sound technically correct, but I have problem to see the importance of the response rates to understand the stability of the systems.

In my opinion 3 main questions are more important in all these discussions:

Author response to Reviewer 3 commment 1
================================================================================

I thank Reviewer 3 for their review, including their comment on the quality of the writing and verification that the calculations and and code are technically correct. In my revision, in line with the comments of the other two reviewers, I have improved the way in which the importance of my results are communicated. I address Reviewer 3's main three questions below.

Reviewer 3 commment 2
================================================================================

1. The diagonal of the matrix, thinking in species interactions, represents the intraspecific interactions in the same species, and in the study of the stability is the main point because it gives us the center of the cloud of eigenvalues. In these study, as many all of them, is taken as -1. All infraspecific interactions in every species are negatives and equal? It is difficult to agree with this idea.

Author response to Reviewer 3 commment 2
================================================================================

The diagonal of the matrix $M$ models component self-regulation, such as species carrying capacity in an ecological community. The relationship between diagonal elements of $M$ and stability is well-known for large circular matrices (e.g., Tang et al. 2014; Allesina and Tang 2015), in which the mean value of diagonal elements determines the center of the eigenvalue distribution on the real axis as $S \to \infty$.

Theoretical studies of community stability assign negative diagonal values (typically -1) to make the simplifying assumption that components of the system are self-regulating (e.g., May 1972, 1973; Sinha 2005; Allesina and Tang 2012; Grilli et al. 2017; Song and Saavedra 2018; Stone 2018). If individual components are not self-regulating, then the system will almost never be stable. I tried this very early on in the process of investigating the effects of $\gamma$ by allowing diagonal elements to be sampled in the same way as off-diagonals: from a normal distribution centred at zero (data are here, note that the tables show the information in a bit more of a confusing format that in the SI, which was subsequently improved prior to my original submission: https://github.com/bradduthie/RandomMatrixStability/blob/dfe6f8e0225733c94348bc9e0dad6218c59cc109/notebook/sim_results_old/oldest/mat_dat.csv). The effect of $\gamma$ on increasing stability is retained, but stability of all systems drops to zero out of one million given size $S > 14$. And in the random systems that are found to be stable, all diagonal elements are nearly always negative (or, rarely, with one or two very low positive values). In other words, if diagonal elements were randomly sampled from a distribution with positive support, then the only systems that would be stable would be those that by chance had all (or nearly all) negative diagonal elements.

Hence, in this paper and nearly all related papers, when assessing stability, it makes sense to assume that individual system components are self-regulating. But this is not necessarily just a simplifying assumption to avoid unnecessary computations. In the case of ecological species, a positive intraspecific interaction value does not make sense. This would imply that the species being modelled did not compete with itself and had no carrying capacity (because intraspecific competition is directly and inversely related to carrying capacity). Since infinite growth is clearly unrealistic, ecological systems represented by random matrices really should have negative diagonal elements.

Unequal diagonal elements could be used, but doing so would only be expected to add some variation around the expected centre of eigenvalue distributions, and would not change my primary result concerning the effect of $\gamma$ (note that this would lead to the same results as mentioned above where diagonal elements were sampled in the same way as off diagonals, but with more total stable systems since the mean diagonal value would be less lower). 

I have tried to clarify and more clearly state the assumption of self-regulation in my revision (paragraphs starting on L28 and L65).

Reviewer 3 commment 3
================================================================================

2. In these discussions the author use random matrix to implement complex systems. Again it is difficult to understand how a random matrix can represent a complex system. If we think in species again, different ecological interactions have different distributions, has can be observed in the paper of Tang and I Sundstrand that the random matrices can be a perfect null model, but nothing more.

Author response to Reviewer 3 commment 3
================================================================================

Reviewer 3 is correct that random matrices are an ideal null model for understanding stability in complex systems such as communities of species. In this manuscript, I use the random matrix approach as a null model to investigate the role played by a property of nearly all complex systems (component response variation) in affecting stability. This approach to investigating stability in complex systems has been used widely since May (1972), and has been refined to more specifically to reflect the properties of systems with a particular structure (e.g., specific ecological interactions; Allesina and Tang 2012). My revision now more extensively simulates the structures of real-world networks, including the cascade foode web model  (e.g., Williams and Martinez 2000), small-world networks (Watts and Strogatz 1998), and scale-free networks (Albert and Barab\'{a}si 2002; see also Author response to Reviewer 2 comment 3).

I have tried to clarify the role of random matrices as a null model of complex system stability (L53-L64).

Reviewer 3 commment 4
================================================================================

3. I can understand the importance of the study of the responds rates to understand the stability of the matrices. Maybe I am wrong but sound like the author is comparing apples and oranges.

Author response to Reviewer 3 commment 4
================================================================================

Component response rates can be modelled using a diagonal matrix in which elements correspond to the rate at which individual system components respond to perturbations in the system (Patel et al. 2018). Hence, such a diagonal matrix $\gamma$ can be multiplied by a random matrix representing a complex system $A$ to produce a complex system in which component response rates vary, $M = \gamma A$. By doing an eigenanalysis on $M$ versus $A$, it is possible to understand how response rates affect stability. Hence, I am not comparing apples and oranges; response rates of components have a clear and important role in complex system stability that can be investigated with the mathematical techniques used in this manuscript. I have tried to explain this role more clearly in my revision by more clearly presenting results in terms of differences between the matrices $A$ and $M$ (this affected many areas throughout the text and SI, with clarification of the comparison presented in L82-L89).

Reviewer 3 commment 5
================================================================================

Other minor questions.

I've missed some classic articles from random-matrix literature as:

H.J. Sommers, A. Crisanti, H. Sompolinsky, and Y. Stein, Spectrum of Large Random Asymmetric Variables, Phys. Rev. Lett. 60, 1895 (1988).

S.E. Townsend, D.T. Haydon, and L. Matthews, On the generality of stability-complexity relationships in Lotka-Volterra ecosystems, J. Theor. Biol. 267, 243 (2010).

A. Mougi, and M. Kondoh, Diversity of Interaction Types and Ecological Community Stability, Science 337, 349 (2012).

K.Z. Coyte, J. Schluter, and K.R. Foster, The ecology of the microbiome: Networks, competition, and stability, Science 350, 663 (2015).


Author response to Reviewer 3 commment 3
================================================================================

I thank Reviewer 3 for pointing out these articles. I have cited them where appropriate (L25, L69, L323, L325, and L367).


Author References within Review
================================================================================

Ahmadian, Y., Fumarola, F., & Miller, K. D. (2015). Properties of networks with partially structured and partially random connectivity. Physical Review E - Statistical, Nonlinear, and Soft Matter Physics, 91(1), 012820. https://doi.org/10.1103/PhysRevE.91.012820

Albert, R., & Barab\'{a}si, A. L. (2002). Statistical mechanics of complex networks. Reviews of Modern Physics, 74(1), 47–97. https://doi.org/10.1103/RevModPhys.74.47

Allesina, S., & Tang, S. (2012). Stability criteria for complex ecosystems. Nature, 483(7388), 205–208. https://doi.org/10.1038/nature10832

Allesina, S., & Tang, S. (2015). The stability–complexity relationship at age 40: a random matrix perspective. Population Ecology, 63–75. https://doi.org/10.1007/s10144-014-0471-0

Dougoud, M., Vinckenbosch, L., Rohr, R., Bersier, L.-F., & Mazza, C. (2018). The feasibility of equilibria in large ecosystems: a primary but neglected concept in the complexity-stability debate. PLOS Computational Biology, 14(2), e1005988. Retrieved from http://arxiv.org/abs/1612.06735

Gibbs, T., Grilli, J., Rogers, T., & Allesina, S. (2017). The effect of population abundances on the stability of large random ecosystems. Arxiv. Retrieved from http://arxiv.org/abs/1708.08837

Grilli, J., Adorisio, M., Suweis, S., Barabás, G., Banavar, J. R., Allesina, S., & Maritan, A. (2017). Feasibility and coexistence of large ecological communities. Nature Communications, 8. https://doi.org/10.1038/ncomms14389

May, R. M. (1972). Will a large complex system be stable? Nature, 238, 413–414.

May, R. M. (1973). Qualitative stability in model ecosystems. Ecology, 54(3), 638–641. https://doi.org/10.2307/1935352

Neri, I., & Metz, F. L. (2012). Spectra of sparse non-Hermitian random matrices: An analytical solution. Physical Review Letters, 109(3). https://doi.org/10.1103/PhysRevLett.109.030602

Patel, S., Cortez, M. H., & Schreiber, S. J. (2018). Partitioning the effects of eco-evolutionary feedbacks on community stability. American Naturalist, 191(3), 1–29. https://doi.org/10.1101/104505

Sinha, S. (2005). Complexity vs. stability in small-world networks. Physica A: Statistical Mechanics and Its Applications, 346(1-2 SPEC. ISS.), 147–153. https://doi.org/10.1016/j.physa.2004.08.062

Song, C., & Saavedra, S. (2018). Will a small randomly assembled community be feasible and stable? Ecology, 99(3), 743–751. https://doi.org/10.1002/ecy.2125

Stone, L. (2018). The feasibility and stability of large complex biological networks: a random matrix approach. Scientific Reports, 8, 8246. https://doi.org/10.1101/223651

Tang, S., & Allesina, S. (2014). Reactivity and stability of large ecosystems. Frontiers in Ecology and Evolution, 2(June), 1–8. https://doi.org/10.3389/fevo.2014.00021

Tao, T., & Vu, V. (2010). Random matrices: Universality of ESDs and the circular law. Annals of Probability, 38(5), 2023–2065. https://doi.org/10.1214/10-AOP534

Watts, D. J., & Strogatz, S. H. (1998). Collective dynamics of “small world” networks. Nature, 393(June), 440–442.

Williams, R. J., & Martinez, N. D. (2000). Simple rules yield complex food webs. Nature, 404(6774), 180–183. https://doi.org/10.1038/35004572






