---
title: "Stability concerns in random matrices"
author: "Brad Duthie"
bibliography: references.bib
output:
  html_document: default
  pdf_document:
    fig_caption: yes
  word_document:
    fig_caption: yes
    pandoc_args:
    - --csl
    - evolution.csl
    reference_docx: docx_template.docx
header-includes:
- \usepackage{amsmath}
- \usepackage{natbib}
- \usepackage{lineno}
- \usepackage[utf8]{inputenc}
- \linenumbers
- \bibliographystyle{amnatnat}
linestretch: 1
link-citations: yes
linkcolor: blue
csl: evolution.csl
biblio-style: apalike
---


<a name="comment_on_Patel">The effect of increasing numbers of evolutionary traits on eco-evolutionary stability</a>
--------------------------------------------------------------------------------

Recently, @Patel2018 demonstrated the stability criteria for eco-evolutionary systems. A key result was that an unstable (stable) ecological community could be stabilised (destabilised) by fast eco-evolutionary feedback, assuming the evolutionary system was itself stable. Likewise, @Patel2018 showed that an unstable (stable) evolutionary system could be stabilised (destabilised) by fast ecological feedback, assuming the ecological community was itself stable. **Here I am going to show why the stability criteria for eco-evolutionary systems is such that stable ecological systems are *increasingly* likely to be destablised, and unstable ecological systems are *decreasingly* likely to be stabilised, at higher numbers of species traits**. I will use a random matrix approach similar to that of Allesina and colleagues [@Allesina2011; @Allesina2012; @Allesina2015a]. The mathematical concept of what I describe below is not new, and is a similar point to what @May1971 explained nearly half a century ago (that increasing species number decreases stability). Still, this point was not, that I can find, noticed or acknowledged by @Patel2018 when coming up with their stability criteria.

**Hence, the goal here is to demonstrate the inherent destabilising effect of rapid evolution, which can also be interpreted as plasticity [@Patel2018], on ecological communities.**

Assume a community of $n$ species, each with the same evolving trait (e.g., body size). Each species $i$ therefore has its own associated trait $m_{i}$ (originally I was thinking about parental investment -- I thought that I had come up with something really interesting, then realised that @Parker1986 got there first). We can describe the dynamics of a system with two species $i$ and $j$ using the Jacobian matrix $\boldsymbol{J}$ below [@Patel2018],

$$\boldsymbol{J} = \begin{bmatrix}
    \boldsymbol{A}  & \boldsymbol{B}  \\
    \boldsymbol{C}  & \boldsymbol{D}  \\  \end{bmatrix}
    = \begin{bmatrix}
    \frac{\partial N_{i}W_{i}}{\partial N_{i}}  & \frac{\partial N_{i}W_{i}}{\partial N_{j}} & \frac{\partial N_{i}W_{i}}{\partial m_{i}} & \frac{\partial N_{i}W_{i}}{\partial m_{j}}  \\
    \frac{\partial N_{j}W_{j}}{\partial N_{i}}  & \frac{\partial N_{j}W_{j}}{\partial N_{j}} & \frac{\partial N_{j}W_{j}}{\partial m_{i}} & \frac{\partial N_{j}W_{j}}{\partial m_{j}} \\
    \varepsilon\frac{\partial m_{i}}{\partial N_{i}}  & \varepsilon\frac{\partial m_{i}}{\partial N_{j}} & \varepsilon\frac{\partial m_{i}}{\partial m_{i}} & \varepsilon\frac{\partial m_{i}}{\partial m_{j}}  \\
    \varepsilon\frac{\partial m_{j}}{\partial N_{i}}  & \varepsilon\frac{\partial m_{j}}{\partial N_{j}} & \varepsilon\frac{\partial m_{j}}{\partial m_{i}} & \varepsilon\frac{\partial m_{j}}{\partial m_{j}}  \\
\end{bmatrix}.$$

Note that the matrix $\boldsymbol{J}$ can be separated into four separate submatrices. The submatrix $\boldsymbol{A}$ describes the effects that the density of one species has on its own population growth (diagonal) or that of another species (off-diagonal). The submatrix $\boldsymbol{B}$ describes the effect the trait $m$ of each species has on the population growth of itself or another species. The submatrix $\boldsymbol{C}$ describes the effect that the density of a species has on a species' changing $m$, and $\boldsymbol{D}$ describes the effect that traits have on traits. The value of $\varepsilon$ defines the rate of evolutionary change relative to ecological change; here I will just assume a high value of $\varepsilon$, but the conclusions regarding an increasing number of traits' effect on a relatively slowly changing ecoogical system will be equally applicable to an incresing number of species in relativley slowly evolving system. I will therefore only assume a high value of $\varepsilon$ for now. 

For the whole system (ecology and evolution) to be stable when traits change quickly relative to population densities, evolution by itself $\boldsymbol{D}$ must be stable. This is the case when all of the eigenvalues of $\boldsymbol{D}$ are negative. Additionally, for the system $\boldsymbol{J}$ as a whole to be stable, we need to consider the feedback between ecology and evolution. @Patel2018 showed that the system as a whole is stable when the following is satisfied, 

$$s\left(\boldsymbol{A} + \boldsymbol{B}\boldsymbol{D}^{-1}(-\boldsymbol{C})\right) < 0.$$

I am specifically interested in the case in which $\boldsymbol{D}$ is known to be stable. Using random matrices containing element values that are real numbers uniformly distributed between $-4$ and $4$, I will show that rapid evolution is almost never stabilising and almost always destabilising when over six species and their traits $m$ are considered. To do this, I will use the following code, which finds a stable random matrix $\boldsymbol{D}$ and assigns random element values (possibly, but not necessarily stable) to $\boldsymbol{A}$, $\boldsymbol{B}$, and $\boldsymbol{C}$. I will do this for 100000 replicates of species numbers from $n = 2$ to $n = 8$.

```{r, echo = TRUE}
random_comm <- function(dm = 2, iter = 10000){
    stabilised_fastevo <- NULL;
    unstabled_fastevo  <- NULL;
    nn           <- dm * dm;
    tot_stabled  <- 0;
    tot_ustabled <- 0;
    tot_eco_stab <- 0;
    stabilised_fastevo <- NULL;
    unstabled_fastevo  <- NULL;
    while(iter > 0){
        stabilised   <- 0;
        unstabilised <- 0;
        Adat <- runif(n = nn, min = -4, max = 4);
        Bdat <- runif(n = nn, min = -4, max = 4);
        Cdat <- runif(n = nn, min = -4, max = 4);
        A    <- matrix(data = Adat, nrow = dm, ncol = dm);
        B    <- matrix(data = Bdat, nrow = dm, ncol = dm);
        C    <- matrix(data = Cdat, nrow = dm, ncol = dm);
        egD  <- 1;
        while(egD >= 0){
             Ddat <- runif(n = nn, min = -4, max = 4);
             D    <- matrix(data = Ddat, nrow = dm, ncol = dm);
             egD  <- max(Re(eigen(D)$values))
        }
        eco_stable       <- max(Re(eigen(A)$values)) < 0;
        slow_evo_maxE    <- max(Re(eigen(A + B %*% solve(D) %*% (-C))$values));
        stable_fast_evo  <- slow_evo_maxE < 0;
        if(eco_stable == FALSE & stable_fast_evo == TRUE){
            list_ele <- length(stabilised_fastevo$A) + 1;
            stabilised_fastevo$A[[list_ele]] <- A;
            stabilised_fastevo$B[[list_ele]] <- B;
            stabilised_fastevo$C[[list_ele]] <- C;
            stabilised_fastevo$D[[list_ele]] <- D;
            stabilised   <- 1;
        }
        if(eco_stable == TRUE & stable_fast_evo == FALSE){
            list_ele <- length(unstabled_fastevo$A) + 1;
            unstabled_fastevo$A[[list_ele]] <- A;
            unstabled_fastevo$B[[list_ele]] <- B;
            unstabled_fastevo$C[[list_ele]] <- C;
            unstabled_fastevo$D[[list_ele]] <- D;
            unstabilised   <- 1;
        }
        if(stabilised == 1){
            tot_stabled <- tot_stabled + 1;
        }
        if(unstabilised == 1){
            tot_ustabled <- tot_ustabled + 1;
        }
        if(eco_stable == TRUE){
            tot_eco_stab <- tot_eco_stab + 1;
        }
        iter <- iter - 1;
    }
    results <- list(ecologically_stable = tot_eco_stab, 
                    stabilised = tot_stabled, destabilised = tot_ustabled,
                    stabilised_all   = stabilised_fastevo, 
                    destabilised_all = unstabled_fastevo);
    return(results);
}
```

Note that the code above takes a while to run for a large number of species, and this is mostly caused by having to find a random matrix $\boldsymbol{D}$ that is stable. The code first checks whether $\boldsymbol{A}$ is stable, and if it is stable, whether or not eco-evolutionary dynamics destabilise the stable ecological community. If it is not stable, then the code checks whether eco-evolutionary dynamics stabilise the unstable ecological community. As expected [@May1971], ecological stability decreases with an increasing number of species.

```{r, echo = FALSE}
dat       <- read.table(file = "rand_sims.txt", header = TRUE);
species   <- dat[,1];
pr_stable <- dat[,2] / (dat[,2] + dat[,4]);
par(mar = c(5, 5, 2, 1));
plot(x = species, y = pr_stable, type = "b", lwd = 2, ylim = c(0, 1),
     xlab = "Species number", ylab = "Proportion stable (n)",
     cex.axis = 1.5, cex.lab = 1.5);
```

More interesting, the plot below shows eco-evolutionary results for ecological communities that **are** stable. The x-axis shows the number of species in the community (recall that each species has the same evolving trait potentially affecting ecology and evolution), and the y-axis shows the proportion of of these communities that are *destabilised* by eco-evolutionary dynamics. 

```{r, echo = FALSE}
pr_destabilised <- dat[,3] / dat[,2];
par(mar = c(5, 5, 2, 1));
plot(x = species, y = pr_destabilised, type = "b", lwd = 2, ylim = c(0, 1),
     xlab = "Species number", ylab = "Proportion destabilised",
     cex.axis = 1.5, cex.lab = 1.5);
```

Note that the proportion of communities that are destabilised by eco-evolutionary effects increases with increasing species number. The plot below shows the eco-evolutionary results for ecological communities that are unstable. The y-axis here shows the proportion of communities that are *stabilised* by eco-evolutionary dynamics. This decreases with increasing species number. 

```{r, echo = FALSE}
pr_stabilised <- dat[,5] / dat[,4];
par(mar = c(5, 5, 2, 1));
plot(x = species, y = pr_stabilised, type = "b", lwd = 2, ylim = c(0, 1),
     xlab = "Species number", ylab = "Proportion stabilised",
     cex.axis = 1.5, cex.lab = 1.5);
```

Hence, overall, **as species number and therefore evolving species traits increases, the probability that stable ecological communities become destabilised increases rapidly and the probability that unstable ecological communities are stabilised becomes vanishingly small**. I am not sure if I can prove this mathematically, but I don't think I need to for the point to be made effectively. What I want to figure out is whether or not this point can or should be published in the peer-reviwed literature -- else it's a blog post.



References
--------------------------------------------------------------------------------




